'use client';

import { useState } from 'react';
import { supabase } from '@/lib/supabase';

// TypeScript interfaces
interface TShirtItem {
  id: number;
  size: string;
  quantity: number;
  pricePerPiece: number;
}

export default function BookingForm() {
  // Customer details state
  const [customerName, setCustomerName] = useState('');
  const [mobileNumber, setMobileNumber] = useState('');
  
  // T-Shirt items state
  const [items, setItems] = useState<TShirtItem[]>([
    { id: 1, size: 'M', quantity: 1, pricePerPiece: 350 }
  ]);
  
  const [nextId, setNextId] = useState(2);
  
  // UI state
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submitMessage, setSubmitMessage] = useState<{ type: 'success' | 'error'; text: string } | null>(null);
  
  // Price per T-Shirt
  const PRICE_PER_T_SHIRT = 350;
  
  // Available sizes
  const availableSizes = ['XS', 'S', 'M', 'L', 'XL', 'XXL', 'XXXL', '4XL', '5XL'];
  const childSizes = ['22', '24', '26', '28', '30', '32'];
  
  // Calculate total shirts
  const calculateTotalShirts = () => {
    return items.reduce((total, item) => total + item.quantity, 0);
  };
  
  // Calculate total price
  const calculateTotal = () => {
    return items.reduce((total, item) => total + (item.quantity * item.pricePerPiece), 0);
  };
  
  // Add new T-Shirt row
  const addTShirt = () => {
    setItems([...items, { id: nextId, size: 'M', quantity: 1, pricePerPiece: PRICE_PER_T_SHIRT }]);
    setNextId(nextId + 1);
  };
  
  // Remove T-Shirt row
  const removeTShirt = (id: number) => {
    if (items.length === 1) {
      alert('किमान एक टी-शर्ट बुक करणे आवश्यक आहे');
      return;
    }
    setItems(items.filter(item => item.id !== id));
  };
  
  // Update item size
  const updateSize = (id: number, size: string) => {
    setItems(items.map(item => 
      item.id === id ? { ...item, size: size } : item
    ));
  };
  
  // Update item quantity - FIXED for mobile!
  const updateQuantity = (id: number, value: string) => {
    // Remove any non-digit characters
    let cleanValue = value.replace(/\D/g, '');
    
    // Handle empty input
    if (cleanValue === '') {
      setItems(items.map(item => 
        item.id === id ? { ...item, quantity: 1 } : item
      ));
      return;
    }
    
    // Convert to number
    let quantity = parseInt(cleanValue, 10);
    
    // Apply limits
    if (isNaN(quantity) || quantity < 1) quantity = 1;
    if (quantity > 20) quantity = 20;
    
    setItems(items.map(item => 
      item.id === id ? { ...item, quantity: quantity } : item
    ));
  };
  
  // Handle quantity change with proper mobile behavior
  const handleQuantityChange = (id: number, e: React.ChangeEvent<HTMLInputElement>) => {
    updateQuantity(id, e.target.value);
  };
  
  // Handle quantity blur - ensure valid number
  const handleQuantityBlur = (id: number, currentQuantity: number) => {
    if (currentQuantity < 1 || isNaN(currentQuantity)) {
      setItems(items.map(item => 
        item.id === id ? { ...item, quantity: 1 } : item
      ));
    }
  };
  
  // Form validation
  const isFormValid = () => {
    if (!customerName.trim()) return false;
    if (!mobileNumber.trim() || mobileNumber.length !== 10 || !/^\d+$/.test(mobileNumber)) return false;
    if (items.length === 0) return false;
    return true;
  };
  
  // Save to Supabase (database auto-generates Order ID)
  const saveToSupabase = async () => {
    try {
      // 1. Insert into orders table (order_id will be auto-generated by database)
      const { data: orderData, error: orderError } = await supabase
        .from('orders')
        .insert({
          customer_name: customerName.trim(),
          mobile_number: mobileNumber,
          total_amount: calculateTotal(),
          total_shirts: calculateTotalShirts(),
          payment_verified: false,
          collected: false,
          created_at: new Date().toISOString()
        })
        .select()
        .single();
      
      if (orderError) throw orderError;
      
      // 2. Insert each T-Shirt into order_items table
      const orderItems = items.map(item => ({
        order_id: orderData.id,
        size: item.size,
        quantity: item.quantity,
        price_per_piece: item.pricePerPiece,
        subtotal: item.quantity * item.pricePerPiece
      }));
      
      const { error: itemsError } = await supabase
        .from('order_items')
        .insert(orderItems);
      
      if (itemsError) throw itemsError;
      
      return { success: true, orderData };
      
    } catch (error: any) {
      console.error('Supabase error:', error);
      return { success: false, error: error.message };
    }
  };
  
  // Handle form submission
  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!isFormValid()) {
      alert('कृपया सर्व माहिती योग्यरित्या भरा');
      return;
    }
    
    setIsSubmitting(true);
    setSubmitMessage(null);
    
    // Save to Supabase (Order ID auto-generated)
    const result = await saveToSupabase();
    
    if (result.success) {
      // Prepare order data for success page
      const orderDataForPage = {
        order_id: result.orderData.order_id,
        customer_name: customerName.trim(),
        mobile_number: mobileNumber,
        total_amount: calculateTotal(),
        total_shirts: calculateTotalShirts(),
        created_at: new Date().toISOString(),
        items: items.map(item => ({
          size: item.size,
          quantity: item.quantity,
          price_per_piece: item.pricePerPiece,
          subtotal: item.quantity * item.pricePerPiece
        }))
      };
      
      // Navigate to success page with order data
      const encodedData = encodeURIComponent(JSON.stringify(orderDataForPage));
      window.location.href = `/success?data=${encodedData}`;
      
    } else {
      // Show error message
      setSubmitMessage({
        type: 'error',
        text: `❌ बुकिंग अयशस्वी: ${result.error}\nकृपया पुन्हा प्रयत्न करा किंवा प्रशासकाशी संपर्क साधा.`
      });
      setIsSubmitting(false);
      
      // Auto-hide message after 10 seconds
      setTimeout(() => {
        setSubmitMessage(null);
      }, 10000);
    }
  };
  
  return (
    <section id="booking-form" className="py-16 bg-white">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        
        {/* Section Header */}
        <div className="text-center mb-10">
          <h2 className="text-3xl md:text-4xl font-bold text-gray-800 mb-3">
            <span className="marathi-text">टी-शर्ट बुकिंग फॉर्म</span>
          </h2>
          <p className="text-gray-600 text-lg">
            कृपया खालील माहिती भरा
          </p>
          <div className="w-24 h-1 bg-gradient-to-r from-orange-500 to-red-500 mx-auto mt-4 rounded-full"></div>
        </div>
        
        {/* Error Message */}
        {submitMessage && submitMessage.type === 'error' && (
          <div className="mb-6 p-4 rounded-lg bg-red-50 border border-red-500 text-red-700">
            <pre className="whitespace-pre-wrap text-sm font-sans">{submitMessage.text}</pre>
          </div>
        )}
        
        <form onSubmit={handleSubmit} className="space-y-8">
          
          {/* Customer Details Section */}
          <div className="bg-gray-50 rounded-xl p-6 shadow-sm">
            <h3 className="text-xl font-bold text-gray-800 mb-4 marathi-text">
              ग्राहक माहिती
            </h3>
            
            <div className="space-y-4">
              {/* Name */}
              <div>
                <label className="block text-gray-700 font-semibold mb-2">
                  पूर्ण नाव <span className="text-red-500">*</span>
                </label>
                <input
                  type="text"
                  value={customerName}
                  onChange={(e) => setCustomerName(e.target.value)}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent"
                  placeholder="उदा. प्रथम पाटील"
                  disabled={isSubmitting}
                />
              </div>
              
              {/* Mobile Number */}
              <div>
                <label className="block text-gray-700 font-semibold mb-2">
                  मोबाईल नंबर <span className="text-red-500">*</span>
                </label>
                <input
                  type="tel"
                  value={mobileNumber}
                  onChange={(e) => setMobileNumber(e.target.value.replace(/\D/g, '').slice(0, 10))}
                  className="w-full px-4 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500 focus:border-transparent"
                  placeholder="9876543210"
                  maxLength={10}
                  disabled={isSubmitting}
                />
                {mobileNumber && mobileNumber.length !== 10 && (
                  <p className="text-red-500 text-sm mt-1">कृपया 10 अंकी मोबाईल नंबर टाका</p>
                )}
              </div>
            </div>
          </div>
          
          {/* T-Shirt Selection Section */}
          <div className="bg-gray-50 rounded-xl p-6 shadow-sm">
            <h3 className="text-xl font-bold text-gray-800 mb-4 marathi-text">
              टी-शर्ट तपशील
            </h3>
            
            <div className="space-y-4">
              {/* T-Shirt Rows */}
              {items.map((item) => (
                <div key={item.id} className="bg-white rounded-lg p-4 border border-gray-200">
                  <div className="grid grid-cols-1 md:grid-cols-4 gap-4 items-end">
                    {/* Size Selection */}
                    <div>
                      <label className="block text-gray-600 text-sm font-semibold mb-1">
                        साईज
                      </label>
                      <select
                        value={item.size}
                        onChange={(e) => updateSize(item.id, e.target.value)}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500"
                        disabled={isSubmitting}
                      >
                        <optgroup label="प्रौढ साईज">
                          {availableSizes.map(size => (
                            <option key={size} value={size}>{size}</option>
                          ))}
                        </optgroup>
                        <optgroup label="बाल साईज">
                          {childSizes.map(size => (
                            <option key={size} value={size}>{size}</option>
                          ))}
                        </optgroup>
                      </select>
                    </div>
                    
                    {/* Quantity - FIXED for mobile */}
                    <div>
                      <label className="block text-gray-600 text-sm font-semibold mb-1">
                        संख्या
                      </label>
                      <input
                        type="number"
                        inputMode="numeric"
                        pattern="[0-9]*"
                        value={item.quantity}
                        onChange={(e) => handleQuantityChange(item.id, e)}
                        onBlur={() => handleQuantityBlur(item.id, item.quantity)}
                        className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-orange-500"
                        min="1"
                        max="20"
                        step="1"
                        disabled={isSubmitting}
                      />
                    </div>
                    
                    {/* Price per piece */}
                    <div>
                      <label className="block text-gray-600 text-sm font-semibold mb-1">
                        प्रति टी-शर्ट किंमत
                      </label>
                      <div className="w-full px-3 py-2 bg-gray-100 rounded-lg text-gray-700">
                        ₹ {item.pricePerPiece}
                      </div>
                    </div>
                    
                    {/* Subtotal & Remove Button */}
                    <div className="flex items-center justify-between gap-2">
                      <div className="flex-1">
                        <label className="block text-gray-600 text-sm font-semibold mb-1">
                          एकूण
                        </label>
                        <div className="w-full px-3 py-2 bg-orange-50 rounded-lg text-orange-700 font-bold">
                          ₹ {item.quantity * item.pricePerPiece}
                        </div>
                      </div>
                      <button
                        type="button"
                        onClick={() => removeTShirt(item.id)}
                        className="text-red-500 hover:text-red-700 font-bold py-2 px-3"
                        disabled={isSubmitting}
                      >
                        🗑️
                      </button>
                    </div>
                  </div>
                </div>
              ))}
              
              {/* Add More Button */}
              <button
                type="button"
                onClick={addTShirt}
                className="w-full py-3 border-2 border-dashed border-orange-300 rounded-lg text-orange-600 font-semibold hover:bg-orange-50 transition-colors"
                disabled={isSubmitting}
              >
                + दुसरी टी-शर्ट भरा
              </button>
            </div>
          </div>
          
          {/* Total Price Section */}
          <div className="bg-gradient-to-r from-orange-50 to-red-50 rounded-xl p-6 shadow-md">
            <div className="flex flex-col md:flex-row justify-between items-center gap-4">
              <div>
                <p className="text-gray-600 text-sm">एकूण टी-शर्ट</p>
                <p className="text-2xl font-bold text-gray-800">
                  {items.reduce((sum, item) => sum + item.quantity, 0)} टी-शर्ट
                </p>
              </div>
              <div className="text-center md:text-right">
                <p className="text-gray-600 text-sm">एकूण देय रक्कम</p>
                <p className="text-4xl font-bold text-orange-600">
                  ₹ {calculateTotal()}
                </p>
              </div>
            </div>
          </div>
          
          {/* Submit Button */}
          <button
            type="submit"
            disabled={!isFormValid() || isSubmitting}
            className={`w-full py-4 text-lg font-bold rounded-lg transition-all ${
              !isFormValid() || isSubmitting
                ? 'bg-gray-300 text-gray-500 cursor-not-allowed'
                : 'bg-gradient-to-r from-orange-600 to-red-600 text-white hover:shadow-lg transform hover:scale-[1.02] cursor-pointer'
            }`}
          >
            {isSubmitting ? 'बुकिंग होत आहे...' : 'बुकिंग सबमिट करा 📝'}
          </button>
          
          <p className="text-center text-sm text-gray-500">
            * सबमिट केल्यानंतर तुम्हाला Order ID मिळेल. कृपया तो नोंदवून ठेवा.
          </p>
        </form>
      </div>
    </section>
  );
}